### ISSUE TITLE
Why can we not change the analyzer for edge_ngram and ngram fields?

### ISSUE THREAD

**Issue by parasgithub** [bennylope/elasticstack#11]
Why can we not change the analyzer for edge_ngram and ngram fields?

**Comment by bennylope** [comment]
There's not much point in changing the analyzer on those fields because those fields are already, and purposefully, _analyzer specific_ in Haystack.

If you want to use a different analyzer to do similar work, I'd recommend just specifying a new field using  [`ConfigurableFieldMixin`](https://github.com/bennylope/elasticstack/blob/master/elasticstack/fields.py#L38).

The only time I can see this being a problem is if you have no control over what fields are used in the `SearchIndex` class(es). If that is indeed a problem I'd consider a pull request to resolve the issue (see the [contribution doc](https://github.com/bennylope/elasticstack/blob/master/CONTRIBUTING.rst#pull-request-guidelines)).
